[workspace]
resolver = "3"
members = [
  "app",
  "shaders/electric",
  "shaders/grid",
  "shaders/particle",
  "shaders/shared",
]

[workspace.package]
version = "0.1.1"
authors = ["konyogony <me@konyogony.dev>"]
edition = "2024"
repository = "https://github.com/konyogony/physics"
license = "MIT"

[workspace.dependencies]
pollster = "0.4.0"
# API
wgpu = {
  version = "29.0.1",
  default-features = false,
  features = [
    "parking_lot",
    "spirv",
    "std",
    "vulkan",
    "vulkan-portability",
    "wgsl",
  ]
}

anyhow = "1.0.98"
bytemuck = { version = "1.24.0", features = ["derive"] }
# rust-gpu
# While `cargo-gpu` is backwards compatible with older rust-gpu versions, easiest is to just match the versions exactly.
cargo-gpu-install = { git = "https://github.com/Rust-GPU/rust-gpu", rev = "c904e5c039676df3409dd7aa61119102109af921" }
env_logger = "0.11.8"
glam = { version = "0.32.0", default-features = false }
raw-window-handle = "0.6.2"
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu", rev = "c904e5c039676df3409dd7aa61119102109af921" }
winit = "0.30.0"

[workspace.lints.rust]
unexpected_cfgs = {
  level = "allow",
  check-cfg = [
    'cfg(target_arch, values("spirv"))',
  ]
}
